name: auth-service

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME:-"Auth Server"}
      DOMAIN_URL: ${DOMAIN_URL:-http://localhost}

      PRIVATE_KEY: ${PRIVATE_KEY:?}
      ALGORITHM: ${ALGORITHM:-RS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES:-1440}

      EMAILS_ENABLED: ${EMAILS_ENABLED:-false}
      EMAILS_SMTP_PORT: ${EMAILS_SMTP_PORT:?}
      EMAILS_SMTP_SERVER: ${EMAILS_SMTP_SERVER:?}
      EMAILS_SMTP_USER: ${EMAILS_SMTP_USER:?}
      EMAILS_SMTP_PASSWORD: ${EMAILS_SMTP_PASSWORD:?}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL:?}
      EMAILS_FROM_NAME: ${EMAILS_FROM_NAME:?}
      EMAILS_RESET_TOKEN_EXPIRE_HOURS: ${EMAILS_RESET_TOKEN_EXPIRE_HOURS:-24}
      EMAILS_VERIFICATION_TOKEN_EXPIRE_HOURS: ${EMAILS_VERIFICATION_TOKEN_EXPIRE_HOURS:-24}

      USERNAME_MIN_LENGTH: ${USERS_USERNAME_MIN_LENGTH:-3}
      USERNAME_MAX_LENGTH: ${USERS_USERNAME_MAX_LENGTH:-32}
      PASSWORD_MIN_LENGTH: ${USERS_PASSWORD_MIN_LENGTH:-8}
      PASSWORD_MAX_LENGTH: ${USERS_PASSWORD_MAX_LENGTH:-32}

      REDIS_URL: ${REDIS_URL:?}

      MONGO_URI: ${MONGO_URI:?}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME:-auth_server}
